### ISSUE TITLE
Initial offset to sarama.OffsetNewest

### ISSUE THREAD

**Issue by jgoodall** [bsm/sarama-cluster#133]
The [README](https://github.com/bsm/sarama-cluster/blob/2ae74ad075d4f088751b8c074f7e88c1020d7687/README.md#consumer-not-receiving-any-messages) states that `sarama's Config.Consumer.Offsets.Initial is set to sarama.OffsetNewest`, but I am not seeing this. For this snippet, the consumer always gets the oldest messages, regardless of the `config.Consumer.Offsets.Initial` value. (servers, group and topics are set outside of the snippet.)

```
	config := cluster.NewConfig()
	config.Consumer.Offsets.Initial = sarama.OffsetNewest
	client, err := cluster.NewClient(servers, config)
	if err != nil {
		log.Fatalf("Error opening client: %s", err.Error())
	}

	consumer, err := cluster.NewConsumerFromClient(client, group, topics)
	if err != nil {
		log.Fatalf("Error opening consumer: %s", err.Error())
	}

	for !client.Closed() {
		select {
		case msg := <-consumer.Messages():
			consumer.MarkOffset(msg, "")
			fmt.Printf("key: %s (%d)\nval: %s\n\n", string(msg.Key), msg.Offset, string(msg.Value))
		}
	}
```

Am I doing something incorrectly?

**Comment by dim** [comment]
It depends. if the `group` has been consumed before and the offset exists, it will always automatically resume from that offset. The `Consumer.Offsets.Initial` setting will only be used if the consumer group doesn't exist or if the stored offset cannot be retrieved (e.g. expired). Delete your consumer-group via the 
`kafka-consumer-groups.sh` tool bundled with Kafka and try again.

**Comment by jgoodall** [comment]
Is there no way to delete the consumer group programatically? I dont see anything in the API...

**Comment by dim** [comment]
We had quite a long discussion in one in #87, the problem is that you have multiple consumers and there is no API on Kafka side that would guarantee synchronisation/exclusive access. Imagine the following scenario:

* You consume a topic from two consumers A (partition 0) and B (partition 1) 
* On A you decide to delete the consumer group (assuming there was an API for it)
* A exits and rebalances
* B in the meantime has no idea that the group was deleted and continues to commit its offsets (effectively re-creating part of that deleted group)
* Rebalance is triggered and A and B are assigned the partitions again
* A resumes from `Consumer.Offsets.Initial` while B resumes from the stored one

As said in the other ticket, I think adding custom synchronisation among consumers to ensure consistency is out of scope for this library. 

So until there is a special API in Kafka (one that disconnects the consumers and then deletes the group before allowing them to rebalance), you can only stop all the consumers first and remove the group manually.
