### ISSUE TITLE
Error if I use sarama as 'gopkg.in/Shopify/sarama.v1'

### ISSUE THREAD

**Issue by lanzi0907** [bsm/sarama-cluster#136]
The code files in bsm/sarama-cluster are based on sarama and they import github.com/Shopify/sarama.
So if I want to use both producer and consumer in my project, and I'd like to use Sarama-cluster to build the consumer, I have to import both Sarama and Sarama-cluster.
If I import Sarama like: '`sarama "gopkg.in/Shopify/sarama.v1" `', and import Sarama-cluster, there would be some type assignment error like:
`cannot use "gopkg.in/Shopify/sarama.v1".CompressionSnappy (type "gopkg.in/Shopify/sarama.v1".CompressionCodec) as type "vendor/github.com/Shopify/sarama".CompressionCodec in assignment`
That's because sarama-cluster import **github.com/Shopify/sarama** but not **gopkg.in/Shopify/sarama.v1**

How can I use sarama-cluster while use sarama with **gopkg.in/Shopify/sarama.v1**?

Thank you very much!

**Comment by dim** [comment]
The use of gopkg.in is deprecated since vendoring was introduced (for the exact same reason you mentioned above). Especially with the release of https://github.com/golang/dep it will become obsolete. That said, you could vendor both, `saramaV1 "gopkg.in/Shopify/sarama.v1"` and `sarama "github.com/Shopify/sarama"` and use them in your package side-by-side
