### ISSUE TITLE
Offset management skipping message

### ISSUE THREAD

**Issue by thanhpk** [bsm/sarama-cluster#148]
I sequently published 2 messages into a topic: `m1`, `m2`
Then I mark offset for m2 by using [consumer.MarkOffset](https://github.com/bsm/sarama-cluster/blob/master/consumer.go#L112), kafka cluster will automatic commit `m2`, **and `m1`**. However `m1` is still being process so if the consumer crash now, kafka will not replay `m1`, `m1` is lost.

I expected that `m2` is not being commit until `m1` is committed

**Comment by dim** [comment]
@thanhpk sorry, but that's not how Kafka works. It will always replay from the last committed offset, so even if you never commit `m1` and only `m2` and your consumer crashes, it will resume from `m3`. 

The limitation of Kafka is that you have to process messages from the same partition sequentially to avoid the scenario mentioned above and that's why Kafka allows you to maintain multiple partitions for a single topic (so you can process messages in parallel).
