### ISSUE TITLE
Race detector flags race in CommitOffsets

### ISSUE THREAD

**Issue by aaronlehmann** [bsm/sarama-cluster#185]
I noticed the Go race detector flagging a data race in a call to `(*Consumer).CommitOffsets`. Here's the trace, from a somewhat old version of `sarama-cluster` (v2.1.6-1-g5d8c110):

```
==================
WARNING: DATA RACE
Read at 0x00c422f64b88 by goroutine 159:
github.com/bsm/sarama-cluster.(*Consumer).CommitOffsets()
     github.com/bsm/sarama-cluster/consumer.go:148 +0x1d4
<my call to CommitOffsets ommitted>

Previous write at 0x00c422f64b88 by goroutine 73:
github.com/bsm/sarama-cluster.(*Consumer).joinGroup()
    github.com/bsm/sarama-cluster/consumer.go:579 +0x664
github.com/bsm/sarama-cluster.(*Consumer).rebalance()
    github.com/bsm/sarama-cluster/consumer.go:467 +0x383
github.com/bsm/sarama-cluster.(*Consumer).mainLoop()
    github.com/bsm/sarama-cluster/consumer.go:237 +0x1a1
```

In my tree, consumer.go:148 is:

```
ConsumerID:              c.memberID,
```

and consumer.go:579 is:

```
c.memberID = resp.MemberId
```

I eyeballed the current master branch, and don't see any changes that look like they would prevent this race.

**Comment by dim** [comment]
@aaronlehmann thanks for this. As you have correctly pointed out, it happens when someone calls `CommitOffsets()` manually while a rebalance is in progress. Now, there is a number of ways for solving this:

1. add a mutex to delay the execution of `CommitOffsets()` until the `rebalance()` is completed. Upside: as a user, you will (probably) get a successful result. Downside: it blocks!
2. we could simply return an error, stating: `"rebalance in progress"`. Upside: doesn't block. Downside: puts the burden on the user to handle these errors.
3. protect only `memberID` and `generationID` with a mutex. Upside: doesn't block either. Downside: the user will (probably) see a number of `"The provided member is not known in the current generation."` errors and I will see a lot of new requests on this issue tracker :)

I prefer solution 2, but please let me know if you have any objections.

**Comment by aaronlehmann** [comment]
I think solution 2 is my preference as well. I am okay with solution 1 as well, but would want to be able to pass in a context to `CommitOffsets` to limit how long it blocks.

**Comment by dim** [comment]
@aaronlehmann pls check the PR above? After some consideration, I have opted for option 3 as there is no "good way" to implement 1 or 2. Added a comment to clarify the matter too.
