### ISSUE TITLE
Consumer-based offset tracking?

### ISSUE THREAD

**Issue by opb** [bsm/sarama-cluster#210]
Hi there

I'm trying to work out if I can use sarama-cluster with consumer-based offset tracking (as opposed to tracking in kafka).

My use case is as follows:

Take a snapshot of a consumer machine at a point in time, with all offsets, etc stored locally on the machine along with copies of the processed data.
I then want to bring up an arbitrary number of copies of this machine, with different consumer group names, and have them all start reading from the offset they have stored locally.

On one hand it looks like vanilla Sarama may be better for this, as I'd have more control over the consumers, but the rebalancing, etc, offered by sarama-cluster would be beneficial.

Any thoughts about how to achieve this would be much appreciated. I note that in master there are now methods to Reset the offset to an earlier value, but this still makes use of kaka-based tracking, which I don't think would work in my scenario.

Many thanks

**Comment by dim** [comment]
@opb sorry for the delay. so what you are looking for is your own, private offset storage? Sorry, I may not understand the bigger picture, but it seems like a hack that is likely to fail. It took Kafka many years to get consumer-group management right, because it is not a trivial problem. Distributing the consumer process to retrieve messages exactly once is hard.

Unfortunately, I don't think I will be able to help. There is no way to abstract the offset tracking mechanism as it relies on Kafka internals, such as join/sync group as well as heartbeats. Sorry

**Comment by opb** [comment]
Hi there

Thanks for the response. Consumer-based offset tracking is an actual thing in Kafka. Rather than a consumer group connecting to the brokers and saying "hey my consumer group ID is xxx, give me the stuff I haven't had yet", you can connect to Kafka and say "hey, for partition 0, the last offset i saw was x, for partition 1 it was y, etc...". 

It's this ability to use a local, consumer-store to get those values of x and y, and set the offset required that is of interest to me. 

Thanks anyway - I've been looking at the confluent library in conjunction with librdkafka, and it looks like it should work.
