### ISSUE TITLE
New partitions are not seen by existing consumers

### ISSUE THREAD

**Issue by bataras** [bsm/sarama-cluster#242]
Using these tools:

- [saram-cluter-cli](https://github.com/bsm/sarama-cluster/blob/master/cmd/sarama-cluster-cli/main.go)
- [kafka manager UI](https://github.com/yahoo/kafka-manager)
- a simple producer writing every second to a topic, logging which topic/partition it went to

Create a single, 1 partition topic.
Run the producer. Then run the CLI tool like this..

`./sarama-cluster-cli -brokers <a broker addr) -group test -topics <a topic> -offset oldest`

The cli tool happily consumes messages. But if you go to the Kafka Manager and add a partition to it, the Producer code sees a rebalance and starts writing alternately to both partitions, but the CLI consumer does not see the new partition and thus starts missing half the messages.

If you stop and rerun the CLI, it sees both partitions and catches up.

Problem is the sarama-cluster consumer needs to be able to automatically pick up new partitions

**Comment by Preylien** [comment]
I just commented on what I believe is the same issue here #170 but I'll give a shorter snippet of what I think the issue is.

This is where it looks like new topics should be picked up:
https://github.com/bsm/sarama-cluster/blob/4d54a79f90a9be10a7829f2957addbb70c550395/consumer.go#L333

Looking at it, if it identifies that a new potential topic exists, the IF returns and therefore exits the loop and doesn't do anything with this new topic.
So as far as I can tell it doesn't actually subscribe to the new topics if it finds any.
It looks like inside this IF the new topic should be subscribed to.

Sorry for double posting, I should have looked at the open issues first

**Comment by bataras** [comment]
This issue is about a consumer not picking up new partitions on an existing topic, while a produce does. It's not about picking up new topics

**Comment by Preylien** [comment]
My bad, I misread your post, and assumed it was related to the problem I was running into. I'll remove it to avoid confusion. 👍

**Comment by dim** [comment]
@Preylien please see my comment on https://github.com/bsm/sarama-cluster/issues/170#issuecomment-404468678.

**Comment by Preylien** [comment]
@dim I don't think this issue is closed. I misread the problem bataras was having, so I believe it should be reopened and looked into separately. Sorry about any confusion.

**Comment by bataras** [comment]
Right. This issue is about a live consumer group not recognizing when a new partition is added to a topic

**Comment by FelixChong** [comment]
May I know if any updates on this issue?

**Comment by dim** [comment]
@FelixChong no updates, sarama-cluster is now officially deprecated since https://github.com/Shopify/sarama/pull/1099 was merged and released. The native sarama implementation makes it easy to watch topics and change subscriptions on rebalances.
