### ISSUE TITLE
Error when staring more consumers than patitions

### ISSUE THREAD

**Issue by riaan53** [bsm/sarama-cluster#29]
Hi,

When starting more consumers than partitions I get the followings error and all consumers rebalances every few seconds until I shut down the extra consumer. 

2016/03/26 08:10:05 Error: kafka server: The provided member is not known in the current generation.

Other kafka client I used just added the extra consumer in a waiting state until a other consumer dies.

Any suggestions?

Thank you.

Regards,
Riaan

**Comment by jotto** [comment]
This is indeed a problem. For comparison the official Java client does this:

* client 0 is successfully consuming from a topic with 1 partition
* client 1 attempts to join the same group as client 0
* client 1 sits idly because there's only 1 partition (it does NOT take over consumption)
* client 0 continues to consume
* user TERM/KILL client 0
* client 1 stops being idle, joins the groups, and takes over consuming

`sarama-cluster` has 2 issues:
1. as @riaan53 noted, constant rebalancing (according to broker logs) (the `sarama-cluster` `mainLoop` func just keeps retrying to join the group every time it gets an error)
2. client 1 takes over consumption (instead of letting client 0 maintain consumption)

These aren't _exactly_ "functional" problems because "high availability" still works (client 0 can take over again if client 1 is TERM/KILL), it's just a lot of broker noise and inconsistent behavior with the Java client.

**Comment by dim** [comment]
Fixed above

**Comment by matbhz** [comment]
@dim can you point the line of code that should've fixed this problem?

In my current topology, I have 3 Consumers consuming from the same consumer group, which has a topic with 12 partitions. In theory, I would be expecting each consumer to claim 4 partitions.

Instead, listening from `Notifications()` chan I see sometimes a client consuming all 12, or 6 or none, and rebalances are non-stop. Messages from the `Error()` channel though, gives me the `kafka server: The provided member is not known in the current generation.	` problem

**Comment by dim** [comment]
@matbhz the problem above is unrelated to yours. As suggested on the other issue, you are likely timing out or your server is not correctly configured. We had similar issues before when we tried more aggressive timeout settings on the server. 

You should definitely check the Kafka server logs, they will contain some clues to what is going on. I can only assume that your client heartbeat is not reaching the server quickly/frequently enough and the server is then marking the client as dead and starting a new rebalance with a new generation. When the heartbeat then eventually arrives at the server you get a `The provided member is not known in the current generation` message as a response.

**Comment by niuzhifa** [comment]
@matbhz I have the same problem. now you had solved it?

**Comment by nitin302** [comment]
Does increasing heartbeat interval and maxprocessingtime fix this issue? I see these errors intermittently and Once they appear, it consistently fails to rebalance 90% of the time.
