### ISSUE TITLE
Is there a way for consumer to subscribe for all topics?

### ISSUE THREAD

**Issue by bpatelcs** [bsm/sarama-cluster#36]
I want to have multiple go routines reading with separate consumer instance but in the same consumer group so that I can test the consumer rebalancing when new topics are added.

**Comment by dim** [comment]
At the moment, there is no sensible way to do that. Technically, we could support e.g. a whitelist/blacklist/regular expressions for topics, instead of naming them individually, but that is also something that you could implement on your end, before calling `NewConsumerFromClient`. 

Unfortunately, it would not solve the problem of rebalancing when new topics are added, as there is no function for this on Kafka's side. You would need to manually probe the list of known topics in regular intervals, then restart your consumers when changes are detected.
