### ISSUE TITLE
Consumers: rebalance synchronization 

### ISSUE THREAD

**Issue by josselin-c** [bsm/sarama-cluster#98]
During rebalance I'd like to be able to execute some code before giving up on a partition.
Basically it would be a mechanism similar to onPartitionsRevoked from the java consumer:
https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

This would give the opportunity to flush local state into a shared datastore for the new consumer to pick-up.
In practice, I do per-partition processing and store the processing state on disk (with something like boltdb). On rebalance, I'd like to synchronize the local state into a compacted topics before another consumer is assigned the partition.

**Comment by josselin-c** [comment]
Any idea? Is it something that could be done with the current sarama-cluster architecture or should there be another client type?

**Comment by dim** [comment]
Apologies for the delay, it's been a busy few weeks/months. 

Just to understand, you want to execute a callback when a partition is due to be released? The process to release partitions is:

1. Stop consuming partitions
2. Wait for MaxProcessingTime for the pending/buffered message to be processed
3. Commit marked offsets
4. Clear partition subscriptions
5. Resume with rebalancing

I was wondering at which point you want to execute your callback? To me it looks as if doing it after as part of the offset commit is the most appropriate place. The main problem is that your callback would have to finish in reasonable time as otherwise the rebalance timeout would kick in.

**Comment by josselin-c** [comment]
Hello

I think the callback would have to be executed between 2 & 3. 

For the rebalance timeout, see: https://cwiki.apache.org/confluence/x/foPHAw  This means that with Kafka client >=0.10.1.0, my rebalance can take an arbitrary long time (request.timeout.ms) as long as I have a thread periodically sending heartbeats (max.poll.interval.ms).

Let me detail the usecase I have. This isn't an urgent mater as I currently have a working implementation in Java. More of a nice to have feature that other people may need.

I'm processing events received from a kafka partition using a very large dataset that is mutated by the messages received from that partition. When a rebalance occurs, I would like to finish processing the current event batch, synchronize the mutated dataset to a global store and then commit the offsets and clear the subscription for each partitions I'm assigned to.

On the other side of the rebalance (on another client), I would like to get some subscriptions, download the dataset for the partitions I'm assigned to, and then resume the procesing.

Downloading/Uploading the dataset to the global store takes several minutes on a local network.

Currently, the part where I download the large dataset when I get a new subscription can be implemented with sarama-cluster's Notification events.

**Comment by hasnickl** [comment]
I believe im running into the same difficulty here. My messages are processed by a pool of goroutines, meaning offsets can be "completed" out of order.

To keep reliability in offset tracking, I have my own offset manager that forces the offsets to increase linearly, holding out-of-order offsets in memory until the missing one comes in (i.e., mark offset 7 8 and 10, it holds on to 10 until 9 is marked).

When a rebalance happens, this causes duplicate messages since a partition is released before i can mark offset 10!

**Comment by sugus-seu** [comment]
My case is the processing takes long time, MaxProcessingTime can't cover. And I don't want to wait too long before rebalance. I wish to ignore(or clear) left messages before rebalance. So the process to release partitions I hope is:
1.Stop consuming partitions
2.Send message to Callback Channel
3.Wait for Callback Return Channel
4.Commit marked offsets
5.Clear partition subscriptions
6.Resume with rebalancing

**Comment by dim** [comment]
I think most of the requirements of this issue would be addressed by https://github.com/bsm/sarama-cluster/pull/160, closing for now
